### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#11]
We can't use Github Actions because that doesn't run `nixosTest`s (unless using a self-hosted runner).

One way to host CI is to setup a Jenkins instance for `github:juspay/*` projects using https://github.com/juspay/jenkins-nix-ci and work on resolving https://github.com/juspay/jenkins-nix-ci/issues/27 which we need to build the `./dev` flake.

**Comment by shivaraj-bh** [comment]
Closing the issue as we have native tests enabled in CI
