### ISSUE TITLE
doc: Some todo checkboxes don't render

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#118]
<img width="468" alt="image" src="https://github.com/juspay/services-flake/assets/3998/fd290a9f-76cc-4345-aafa-2d0bda011ba2">

https://community.flake.parts/services-flake/services

**Comment by shivaraj-bh** [comment]
Fixed it here: https://github.com/juspay/services-flake/commit/d8b6d22c5cc7d4df4da52fcc4d643787871db49f
