### ISSUE TITLE
CI: binary cache requests by github-runners are blocked

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/services-flake#126]
Due to large number of requests to fetch the cache stored in `magic-nix-cache`, github responds with:
```
response body:

       GitHub API error: API error (429 Too Many Requests): StructuredApiError { message: "Request was blocked due to exceeding usage of resource 'Count' in namespace ''." }; retrying in 257 ms
```

triggering rebuild of several packages.

## Possible solution

Can we use garnix cache instead?

**Comment by srid** [comment]
> Can we use garnix cache instead?

https://github.com/juspay/services-flake/pull/40#issuecomment-1673421501

https://github.com/garnix-io/issues/issues/61

**Comment by srid** [comment]
Generally, let's not blocker ourselves if the public actions breaks. Let's run nixci locally and merge PRs. We did make a request for mac minis, and will be setting up self-hosted runners. soon.

As for this issue, perhaps we can just switch to cachix?
