### ISSUE TITLE
Write docs for all services

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#132]
The following services are missing docs:

- [x] Apache Kafka
- [x] [[clickhouse]]#
- [x] Elasticsearch
- [x] MySQL
- [x] Nginx
- [x] PostgreSQL
- [x] Redis
- [x] Redis Cluster
- [x] Zookeeper
- [x] [[grafana]]#
- [x] [[prometheus]]#
- [x] [[pgadmin]]#
- [x] [[cassandra]]#
- [x] Grafana tempo

**Comment by shivaraj-bh** [comment]
MySQL: https://github.com/juspay/services-flake/pull/157
