### ISSUE TITLE
postgres: Document socket length limitation and workaround

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#139]
<img width="822" alt="image" src="https://github.com/juspay/services-flake/assets/3998/fd4e864c-3c37-4840-a9f2-3c13d89e43e7">

https://github.com/juspay/services-flake/pull/77

**Comment by srid** [comment]
We may want to have a separate page, `guide/datadir.md`, first and then talk about this. Then we can link to it from `postgresql.md`.

**Comment by srid** [comment]
Also, is $HOME the best place? Why not $TMPDIR (falling back to `/tmp`)?

**Comment by shivaraj-bh** [comment]
on darwin `TMPDIR` seems to be set, but that’s not the case in my NixOS. Not sure how it is in other linux distros. Perhaps if this is not set, we can fallback to `/tmp`?

**Comment by shivaraj-bh** [comment]
> We may want to have a separate page, `guide/datadir.md`, first and then talk about this. Then we can link to it from `postgresql.md`.

https://github.com/juspay/services-flake/pull/144

**Comment by shivaraj-bh** [comment]
postgres doc mentioning the socket length limitation: https://github.com/juspay/services-flake/pull/147

**Comment by shivaraj-bh** [comment]
> Also, is $HOME the best place? Why not $TMPDIR (falling back to `/tmp`)?

This might not be as straight forward as it seems. Let’s assume that the `socketDir` option is set to “$TMPDIR/<some-path>”, we can check for the presence of `$TMPDIR` in the shell script, but how do we then propagate the final socketDir path (after fallback to /tmp), to the [settings option](https://github.com/juspay/services-flake/blob/18f9decf139fca00ae6a19697e4ee16d10363270/nix/postgres/default.nix#L198-L203)?

**Comment by srid** [comment]
What happens if we don't set this option in the first place? What is postgres' default -- and is that sufficient?

https://github.com/juspay/services-flake/blob/18f9decf139fca00ae6a19697e4ee16d10363270/nix/postgres/default.nix#L201

**Comment by shivaraj-bh** [comment]
> What happens if we don't set this option in the first place? What is postgres' default -- and is that sufficient?
> 
> https://github.com/juspay/services-flake/blob/18f9decf139fca00ae6a19697e4ee16d10363270/nix/postgres/default.nix#L201

It will use `dataDir` by default

**Comment by srid** [comment]
> The default value is normally /tmp, but that can be changed at build time. 

https://www.postgresql.org/docs/current/runtime-config-connection.html

So, the nixpkgs package uses something else as default?

Also, it looks like we can disable this entirely:

>  An empty value specifies not listening on any Unix-domain sockets, in which case only TCP/IP sockets can be used to connect to the server.

(Will that break anything in CI though?)

**Comment by shivaraj-bh** [comment]
I was looking to disable, let me try it out.

**Comment by srid** [comment]
> Due to [socket path limits](https://github.com/cachix/devenv/issues/540), the `DEVENV_RUNTIME` environment variable has been introduced: pointing to `$XDG_RUNTIME_DIR` by default and falling back to `/tmp`.

https://devenv.sh/blog/2023/03/20/devenv-10-rewrite-in-rust/#devenv_runtime
