### ISSUE TITLE
Nginx config file location doesn't support relative imports

### ISSUE THREAD

**Issue by szucsitg** [juspay/services-flake#173]
Currently due to the fact that nginx config is directly pointing to Nix store's location, complex Nginx setup cannot be imported with relative references to the config file.

If the config would be symlinked to dataDir, that would make it trivial to do within the project.

**Comment by srid** [comment]
I'd like to understand the [original](https://xyproblem.info/) problem being solved. Could you state what those *relative references* to the config file in the Nix store are? 

I'm wondering why this wouldn't work for you: create a derivation that contains the master config file, along with these relative references in the same directory ... and then pass that to services-flake.

**Comment by szucsitg** [comment]
Again, the issue is not specifically for config file, but this was the minimal reproducible config. I can link any config, the issue is that I don't want to put into store the local environment certificates, that lives under in our case `./data/mkcert/`. Why `../mkcert/localhost.pem` will work in the config
