### ISSUE TITLE
Refactor(DRY): `./data/${name}`

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#200]
Easy to break this convention in new PRs

![image](https://github.com/juspay/services-flake/assets/3998/3f819011-8197-40c9-9aa8-3c5e0fcc2dd7)

e.g.:  https://github.com/juspay/services-flake/pull/195#discussion_r1615217405

**Comment by shivaraj-bh** [comment]
Shouldn't https://github.com/juspay/services-flake/issues/53 prevent this?

**Comment by srid** [comment]
Only if contributors always use that template and promise to never hand edit the generated `dataDir` option.

**Comment by srid** [comment]
Should we add `namespace` to this consideration as well?

c. https://github.com/juspay/services-flake/pull/219#issuecomment-2166758801

**Comment by shivaraj-bh** [comment]
`namespace` and `dataDir` are going to follow the same convention across services, so how about creating a default module and importing it in https://github.com/juspay/services-flake/blob/main/nix/lib.nix?

**Comment by srid** [comment]
Good idea.

**Comment by srid** [comment]
This should be fairly simply to implement after #258
