### ISSUE TITLE
`example/llm` creates data files in `$PWD`

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#229]
<img width="229" alt="image" src="https://github.com/juspay/services-flake/assets/3998/93b3edf4-7144-4de6-9d4d-c48dc5a546e5">

**Comment by srid** [comment]
In #228, I fixed the `data/open-webui1` part ... but `.webui_secret_key` is still created in `$PWD`.

**Comment by shivaraj-bh** [comment]
we can temporarily fix it by setting `WEBUI_SECRET_KEY` env: https://github.com/open-webui/open-webui/blob/162643a4b17edc24426980e4eddcdcfd7c3f7970/backend/config.py#L706-L711
