### ISSUE TITLE
add baseDataDir which could be shared between services 

### ISSUE THREAD

**Issue by adrian-gierakowski** [juspay/services-flake#23]
I'd like to override default base `dataDir` for all services, without having to re-state service name in each override

I'd like to do this:

```nix
let
  baseDataDir = "./.data";
in {
  services.redis."redis-1" = {
    enable = true;
    inherit baseDataDir;
  };
  services.postgres."pg-1" = {
    enable = true;
    inherit baseDataDir;
  };
}
```

instead of:

```nix
let
  baseDataDir = "./.data";
in {
  services.redis."redis-1" = {
    enable = true;
    dataDir = "${baseDataDir}/redis-1";
  };
  services.postgres."pg-1" = {
    enable = true;
    dataDir = "${baseDataDir}/pg-1";
  };
}
```

while preserving the original data dir structure

see possible implementation [here](https://github.com/rhinofi/services-flake/commit/e35c04f9203755877bce446edb51f7db94824c9c)

**Comment by shivaraj-bh** [comment]
+1 for this issue. If you can raise the PR, more than happy to merge it.

**Comment by adrian-gierakowski** [comment]
here it is: https://github.com/juspay/services-flake/pull/24
thanks!

**Comment by srid** [comment]
Another way to solve this, @adrian-gierakowski :

```nix
let
  imports = [ ({ name, ... }: {
    dataDir = "./.data/${name}";
  } )];
in {
  services.redis."redis-1" = {
    inherit imports
    enable = true;
  };
  services.postgres."pg-1" = {
    inherit imports;
    enable = true;
  };
}

```

**Comment by adrian-gierakowski** [comment]
Happy to close https://github.com/juspay/services-flake/issues/23#issuecomment-1643835355
