### ISSUE TITLE
`example/llm`: Re-evaluate open-webui environment variables

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#230]
https://github.com/juspay/services-flake/blob/f360c8f2bc7e23c858dcb4eb9f597e8a91bba6d2/example/llm/flake.nix#L48-L58

Keep only environment variables (which were introduced in #227) that are strictly necessary, while leaving the rest commented out.

Consider the implications of `DEVICE_TYPE = "cpu";` especially when [GPU](https://community.flake.parts/services-flake/ollama#acceleration) is enabled.

---

Our examples should a) "just work", be b) simple and minimal, c) well-documented (liberal use of comments, for example).

**Comment by shivaraj-bh** [comment]
We needn’t have to assign `DEVICE_TYPE = “cpu”` as [it is `”cpu”` by default](https://github.com/open-webui/open-webui/blob/162643a4b17edc24426980e4eddcdcfd7c3f7970/backend/config.py#L827-L832), unless explicitly specified. 

Also, this ENV doesn’t affect `ollama` using CPU or not, which will [still be managed as documented.](https://community.flake.parts/services-flake/ollama#acceleration), but it only affects how the embedding models used to run RAG pipelines are invoked.

**Comment by shivaraj-bh** [comment]
`ENABLE_OLLAMA_API = "True”;` is also redundant [as it is `true` by default](https://github.com/open-webui/open-webui/blob/162643a4b17edc24426980e4eddcdcfd7c3f7970/backend/config.py#L417-L421). It could probably be a comment so that the users know how to disable it, if they want to.

**Comment by shivaraj-bh** [comment]
`OLLAMA_BASE_URL = "http://${host}:${toString port}”;` is also redundant as it is [derived from `OLLAMA_API_BASE_URL` by default](https://github.com/open-webui/open-webui/blob/162643a4b17edc24426980e4eddcdcfd7c3f7970/backend/config.py#L431-L436).

**Comment by shivaraj-bh** [comment]
```nix
{
  RAG_EMBEDDING_ENGINE = "ollama"; 
  RAG_EMBEDDING_MODEL = "mxbai-embed-large:latest"; 
}
```

should be fine, since otherwise Open WebUI will use [sentence-transformers](https://pypi.org/project/sentence-transformers/)  to fetch the embedding models, which would require `DEVICE_TYPE` to choose where the embedding occurs. If we rely on `ollama` instead, we can make use of already documented configuration to use GPU acceleration.

**Comment by srid** [comment]
> should be fine, since otherwise Open WebUI will use [sentence-transformers](https://pypi.org/project/sentence-transformers/) to fetch the embedding models, which would require `DEVICE_TYPE` to choose where the embedding happens. If we rely on `ollama` instead, we can make use of [already documented configuration to use GPU acceleration](https://community.flake.parts/services-flake/ollama#acceleration).

This, verbatim, sounds like a good candidate for a comment on top of these env vars. 

The rest can be either commented or removed.
