### ISSUE TITLE
expose multiService function on lib output

### ISSUE THREAD

**Issue by adrian-gierakowski** [juspay/services-flake#25]
I found [multiService](https://github.com/juspay/services-flake/blob/321ef32a28ed0e59160cf130c3a7c55e3b979e85/nix/default.nix#L8-L33) useful for defining my local services, so ended up copying the code.

**Comment by srid** [comment]
PR welcome on this one as well. You can expose a `lib` attrset from top-level flake.nix containing this function (defined in `./nix/lib.nix`).
