### ISSUE TITLE
pg's `-init` process must fail with non-zero exit in schema run failures

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#256]
<img width="818" alt="image" src="https://github.com/juspay/services-flake/assets/3998/7899786d-649e-4092-9431-d230fa56f1bc">

https://github.com/juspay/services-flake/blob/4eee29c6a00aa420f6d407602397c24b5dd92998/nix/postgres/setup-script.nix#L51

**Comment by shivaraj-bh** [comment]
https://github.com/juspay/services-flake/pull/209 should have fixed it. Let me try reproducing it, I should also include a test for this scenario.

**Comment by srid** [comment]
Oops, I forgot that I had already opened an issue for it. Let me try latest.

**Comment by srid** [comment]
```
• Updated input 'services-flake':
    'github:juspay/services-flake/218fa6cc9a875c20def622e974fb4e0f391b3b6d' (2024-03-07)
  → 'github:juspay/services-flake/4eee29c6a00aa420f6d407602397c24b5dd92998' (2024-07-03)
```

<img width="849" alt="image" src="https://github.com/juspay/services-flake/assets/3998/2fdd6b24-7c41-4349-a2de-94cd60b8341e">
