### ISSUE TITLE
Dealing with non-root $PWD

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#26]
```
cd ./example
mkdir tmp
cd ./tmp
nix run
```

This creates the data diretory in `./example/tmp/data` (instead of `./example/data` as one would expect -- ie. in flake root). What is the best way to address this? In nammayatri we use `flake-root` + `mission-control` module to side-step the problem. 

One possible solution here is to have services-flake *require* the use of `flake-root` module, and have the data directory use the flake root directory determined by the latter module.

**Comment by srid** [comment]
In some cases (where you are providing services to external users to be run via, say, `nix run github:user/repo#blah`), there is no such concept of flake root - so we should respect $PWD in these cases. 

If we are using flake-root to solve this, then there should be a way to disable it, such as via a `cdToProjectRoot` option (cf. https://github.com/Platonic-Systems/mission-control/pull/29).

**Comment by adrian-gierakowski** [comment]
How about resolving the dir in the following order:

1. if [PRJ_ROOT](https://github.com/numtide/prj-spec/blob/main/PRJ_SPEC.md#specification) is set, use that
2. otherwise try flake root
3. finally fallback on `$PWD`

**Comment by adrian-gierakowski** [comment]
> If we are using flake-root to solve this, then there should be a way to disable it, such as via a cdToProjectRoot

:+1:

**Comment by srid** [comment]
I'm happy to add support for setting `PRJ_ROOT` in `github:srid/flake-root` if that env var is widely used. So, your sequence is narrowed down to (1) and (3) only. 

The problem with resolving dir in an order like this is that the behaviour is no longer deterministic within the process-compose configuration. If you use flake-root, it behaves one way. If you don't, the same `config.process-compose.<name>` behaves differently. That's a bit of magic I'd like to avoid, and instead go for an explicit and local approach.

**Comment by srid** [comment]
Maybe this should be solved upstream, in `process-compose-flake`. See https://github.com/Platonic-Systems/process-compose-flake/pull/29 by @MrFoxPro

**Comment by srid** [comment]
Is this really a problem that's worth solving in process-compose-flake / services-flake? I'm getting convince that we should not. And instead document this, pointing users towards using mission-control + flake-root for a devShell experience.
