### ISSUE TITLE
Improve postgres service for use in nammayatri

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#3]
https://github.com/juspay/passetto/pull/1/files#diff-d42ce6f4af2f6535fe936e696b7866ae0667acb573988e991dce1e76e03f84d1R34-R37

<img width="458" alt="image" src="https://github.com/juspay/services-flake/assets/3998/b7643a59-2110-42f9-ad0a-3dbc7a430c17">

**Comment by shivaraj-bh** [comment]
I see that `initdbArgs` is already an option under `postgres.nix` only thing that I have to add is an option to specify `POSTGRES_HOST_AUTH_METHOD`, right?

**Comment by srid** [comment]
I'd think so, yes.

But, IIRC using `initdbArgs` in passetto didn't work for some reason. 

Ultimately, we want to make sure that the passetto PR works after this change (whatever that is).

**Comment by shivaraj-bh** [comment]
As per discussion with @srid over a call. The following is the checklist to verify if the change made to resolve the issue works:
- [ ] `nix run` on `github:/nammayatri/passetto/nixify` should start all the services on darwin (atm only works on linux)
- [ ] Running `nix run` after uncommenting [`initdbArgs`](https://github.com/juspay/passetto/pull/1/files#diff-d42ce6f4af2f6535fe936e696b7866ae0667acb573988e991dce1e76e03f84d1R34-R37) should start the services.

**Comment by shivaraj-bh** [comment]
This [PR](https://github.com/juspay/services-flake/pull/7) will allow you to manage user authentication methods by letting you configure `pg_hba.conf` file in Nix. Allowing us to get rid of `POSTGRES_INITDB_ARGS = "--auth=scram-sha-256"` and `POSTGRES_HOST_AUTH_METHOD = "scram-sha-256"`. 

Check [here](https://github.com/nammayatri/passetto/pull/1) to see this in action on `passetto` repo.

**Comment by shivaraj-bh** [comment]
Closing this issue as it has been resolved in https://github.com/nammayatri/passetto/pull/1
