### ISSUE TITLE
Why are some services `WIP`?

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#316]
For example,

https://community.flake.parts/services-flake/nginx

<img width="767" alt="image" src="https://github.com/user-attachments/assets/78b3c186-4b98-47b2-aa97-f377f8338ca3">

Does this mean nginx is not fully done? 

If these are not in fact work in progress, please remove them from the docs to make it less confusing. Also, the link is broken.

**Comment by shivaraj-bh** [comment]
It means documentation is WIP, I will replace them with a basic introduction.

**Comment by shivaraj-bh** [comment]
resolved in https://github.com/juspay/services-flake/pull/318
