### ISSUE TITLE
Re-evaluate `max_restarts`

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#317]
Should we make it a default in process-compose-flake? Or perhaps file an issue in process-compose itself asking what the recommend default should be, and why that default is not in process-compose itself.

>  Wasn't this used to be the case before? I vaguely remember process restarts never being infinite to begin with (I've seen processes enter into 'exited' state in process-compose window).
> 
> In any case, this change only affects services. Should we make it a default in process-compose-flake? Actually why not make it a default in `process-compose` itself?
> 
> Incidentally, there's no guarantee that a new service added to the repo will follow the same max_restarts convention. It is easy to miss that, so we should think about solving this more fundamentally.

_Originally posted by @srid in https://github.com/juspay/services-flake/pull/311#pullrequestreview-2280223552_

**Comment by shivaraj-bh** [comment]
How about having the common settings in https://github.com/juspay/services-flake/blob/5e6aba2ac29ad1d3a157e4bf4eb76dac630cf7cd/nix/lib.nix#L39-L41

Except for the `exec.command` most of the other things are common across services:
https://github.com/juspay/services-flake/blob/5e6aba2ac29ad1d3a157e4bf4eb76dac630cf7cd/nix/services/redis.nix#L68-L82

**Comment by shivaraj-bh** [comment]
> Or perhaps file an issue in process-compose itself asking what the recommend default should be

https://github.com/F1bonacc1/process-compose/discussions/242

**Comment by srid** [comment]
Ideal solution: upstream a sensible value for max_restarts.

If that is not practical, yes, we can make these common settings to be shared.
