### ISSUE TITLE
Support using Redis with UDS

### ISSUE THREAD

**Issue by niklasmohrin** [juspay/services-flake#352]
Redis has the option to connect via unix domain sockets. I have such a setup running with
```nix
services.redis."r1" = {
    enable = true;
    port = 0; # disable listening via TCP
    extraConfig = ''
      locale-collate "C"
      unixsocket ../redis.socket
      unixsocketperm 777
    '';
  };
};
settings.processes."r1".readiness_probe.exec.command = lib.mkForce "true";
```
The `../redis.socket` places the socket in the data directory instead of next to the `dump.rdb` file. The `locale-collate` setting should be unneeded for this, but I haven't checked if it is relevant for UDS.

The change in the readiness probe is needed because the current command, `${config.package}/bin/redis-cli -p ${toString config.port} ping` relies on TCP being active. If setup properly, this should probably perform the same ping, but through the socket.

It would be nice if there would be an option like `uds = "data/redis.socket"` to take care of all of this. Please let me know what you think :)

**Comment by shivaraj-bh** [comment]
Could you check if https://github.com/juspay/services-flake/pull/353 works for you?
