### ISSUE TITLE
Add redis

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#6]
Based on https://github.com/cachix/devenv/blob/main/src/modules/services/redis.nix

**Goal**: to be usable in the following,

1. nammayatri Backend
1. https://github.com/nammayatri/location-tracking-service (see PR `#2` in that repo)

Test on (2) before merging.

**Comment by aravindgopall** [comment]
we might need redis-cluster service too.

**Comment by shivaraj-bh** [comment]
I have created a separate issue to track the redis cluster service: #15
