### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#82]
We are on our way to making an initial release and doing formal announcement.

Checklist:

- [x] Finish documentation (sufficiently)
- [x] Create release tag, with empty CHANGELOG.md
  - [x] For future PRs, setup guidelines to update the CHANGELOG
    - auto-generate CHANGELOG from commits. The commits will now follow specification from: https://www.conventionalcommits.org/en/v1.0.0/#summary, after: https://github.com/juspay/services-flake/pull/121
- [x] Blog post 
- [x] Announce.

After this release, we will record all changes in the CHANGELOG.md

**Comment by shivaraj-bh** [comment]
https://github.com/juspay/services-flake/pull/83

will this suffice for documentation? I was thinking of adding doc for one of the services, but I am not entirely sure what more than which is already available in their respective test files can I add?

**Comment by shivaraj-bh** [comment]
Maybe add documentation for development?

**Comment by srid** [comment]
> https://github.com/juspay/services-flake/pull/83 will this suffice for documentation?

I'd say yes.

> Maybe add documentation for development?

Like how to hack on this repo, to add a new service or add a fix? Sure.

**Comment by srid** [comment]
> Blog post and announce.

Does it make sense to combine this with the nammayatri services post?

**Comment by shivaraj-bh** [comment]
> Does it make sense to combine this with the nammayatri services post?

I think yes it does

**Comment by shivaraj-bh** [comment]
One step closer to the finishing the documentation sufficiently:
https://github.com/juspay/services-flake/pull/112

**Comment by shivaraj-bh** [comment]
Blog post draft for announcement: https://github.com/nixos-asia/website/pull/28

**Comment by shivaraj-bh** [comment]
changelog: https://github.com/juspay/services-flake/pull/119

**Comment by shivaraj-bh** [comment]
Blog-post: https://nixos.asia/en/blog/replacing-docker-compose

Announcement:
- Discourse: https://discourse.nixos.org/t/replacing-docker-compose-with-nix-for-development/40912
- Reddit: https://www.reddit.com/r/NixOS/s/McTx5xTTjW
- X (formerly twitter): https://x.com/nixos_asia/status/1765454823066108125?s=20

**Comment by srid** [comment]
@shivaraj-bh I added comparison table in #135.

You can close this issue after announcing the project in Discourse.

**Comment by shivaraj-bh** [comment]
announced in discourse: https://discourse.nixos.org/t/announcing-services-flake/41338?u=shivaraj-bh
