### ISSUE TITLE
Multiple services

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#9]
cf. "*This also solves the problem of only being able to run one instance at a time.*" of https://github.com/cachix/devenv/issues/75

## Consider this scenario

`passetto` adds a postgresql service. But the user (nammayatri) may add their own postgresql service. Can the two DB coexist? 

## What we can do

Should we adjust the module API to accomodate for this? For eg., instead of:

```nix
services.postgresql.enable = true;
```

do we instead do:

```nix
services.postgresql."some-name".enable = true;
```

And consistently use this API for all services?

## Concrete goal

This should work in nammayatri which has [its own postgresql](https://github.com/nammayatri/nammayatri/blob/55c501f4e79fe1b9d7d8b78b52db3f7d1374616d/Backend/nix/arion-configuration.nix#L11-L14), as well as [a postgres db used for passeto](https://github.com/nammayatri/nammayatri/blob/55c501f4e79fe1b9d7d8b78b52db3f7d1374616d/Backend/nix/arion-configuration.nix#L107-L110).

**Comment by shivaraj-bh** [comment]
This makes sense! I think we can already do this if have a different dataDir and serve on a different port.

**Comment by srid** [comment]
It would look more like this,

```nix
services.postgresql = lib.mkOption {
  type = types.submodule ({name, ...}: {
    options = {
      dataDir = lib.mkOption {
        type = types.str;
        default = "./data/${name}";
      };
    }
  });
}
```

Note how `dataDir`'s default is determined from the attrset key (`name`).
